In [32]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline 
from sklearn.cross_validation import train_test_split
from sklearn import preprocessing
from random import random,randint,seed,sample 
from sklearn.preprocessing import StandardScaler
import random as rn
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn import tree 
from sklearn.linear_model import LogisticRegression 

In [8]:
ab=pd.read_csv('/home/abraham/ML-ITAM/Den/Machine_Learning/abalone.csv')
ab.head()

Sex  Length  Diameter  Height  Whole_weight  Shucked_weight  Viscera_weight  \
0   M   0.455     0.365   0.095        0.5140          0.2245          0.1010   
1   M   0.350     0.265   0.090        0.2255          0.0995          0.0485   
2   F   0.530     0.420   0.135        0.6770          0.2565          0.1415   
3   M   0.440     0.365   0.125        0.5160          0.2155          0.1140   
4   I   0.330     0.255   0.080        0.2050          0.0895          0.0395   

   Shell_weight  Rings  
0         0.150     15  
1         0.070      7  
2         0.210      9  
3         0.155     10  
4         0.055      7

In [91]:
list(ab)

['Sex',
 'Length',
 'Diameter',
 'Height',
 'Whole_weight',
 'Shucked_weight',
 'Viscera_weight',
 'Shell_weight',
 'Rings']

In [86]:
X=np.array(ab.iloc[:,1:9])
y=np.array(ab.iloc[:,0])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=6)

In [87]:
scalerx = preprocessing.StandardScaler().fit(X_train)
X_train=scalerx.transform(X_train)
X_test=scalerx.transform(X_test)

In [88]:
rl=LogisticRegression(C=0.01,penalty='l2')
rl.fit(X_train,y_train)
pred=rl.predict(X_test) 
from sklearn.metrics import classification_report,confusion_matrix 
print(classification_report(y_test,pred))
print(confusion_matrix(y_test,pred))

             precision    recall  f1-score   support

          F       0.50      0.26      0.34       269
          I       0.60      0.81      0.69       254
          M       0.46      0.53      0.50       313

avg / total       0.52      0.53      0.51       836

[[ 69  51 149]
 [  6 206  42]
 [ 63  84 166]]


**Ahora usamos Clusters**

In [44]:
from sklearn.cluster import KMeans 
#X = np.array(ab)
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
kmeans.labels_

clases=kmeans.predict(X)

#kmeans.cluster_centers_


In [47]:
clas=np.unique(clases)

In [115]:
e=np.column_stack((y,X,clases))
e

array([['M', 0.455, 0.365, ..., 15.0, 2, 2],
       ['M', 0.35, 0.265, ..., 7.0, 1, 1],
       ['F', 0.53, 0.42, ..., 9.0, 0, 0],
       ..., 
       ['M', 0.6, 0.475, ..., 9.0, 0, 0],
       ['F', 0.625, 0.485, ..., 10.0, 0, 0],
       ['M', 0.71, 0.555, ..., 12.0, 0, 0]], dtype=object)

In [116]:
X=e[:,1:10]  
y=e[:,0]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=6)

In [117]:
c_train=X_train[:,8]
c_test=X_test[:,8]
X_train=X_train[:,0:8]
X_test=X_test[:,0:8]
scalerx = preprocessing.StandardScaler().fit(X_train)
X_train=scalerx.transform(X_train)
X_test=scalerx.transform(X_test)

X_train

/home/abraham/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:444: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[ 0.34719341,  0.4779207 , -0.22472713, ...,  0.76739432,
         0.44641135,  0.01917385],
       [-1.85405186, -1.88455659, -1.76230958, ..., -1.40021557,
        -1.48731392, -1.53567661],
       [ 0.43025927,  0.52818617,  1.19457975, ...,  0.56744708,
         0.73448961,  0.95208413],
       ..., 
       [-1.23105792, -1.33163637, -1.28920729, ..., -1.18209131,
        -1.27845718, -0.91373642],
       [-1.31412378, -1.38190185, -1.28920729, ..., -1.19572407,
        -1.2100386 , -0.91373642],
       [ 0.22259462,  0.17632785,  0.13009959, ..., -0.08238146,
        -0.01451385,  0.01917385]])

In [ ]:
rl=LogisticRegression(C=0.01,penalty='l2')
rl.fit(X_train,y_train)

In [ ]:
pred=rl.predict(X_test) 

In [121]:
X_train0,y_train0=X_train[np.where(c_train==0)],y_train[np.where(c_train==0)]
X_train1,y_train1=X_train[np.where(c_train==1)],y_train[np.where(c_train==1)]
X_train2,y_train2=X_train[np.where(c_train==2)],y_train[np.where(c_train==2)]

X_test0,y_test0=X_test[np.where(c_test==0)],y_test[np.where(c_test==0)]
X_test1,y_test1=X_test[np.where(c_test==1)],y_test[np.where(c_test==1)]
X_test2,y_test2=X_test[np.where(c_test==2)],y_test[np.where(c_test==2)]

In [123]:
rl=LogisticRegression(C=0.01,penalty='l2')
 

In [124]:

rl.fit(X_train0,y_train0)
pred0=rl.predict(X_test0)
rl.fit(X_train1,y_train1)
pred1=rl.predict(X_test1)
rl.fit(X_train2,y_train2)
pred2=rl.predict(X_test2)


In [136]:
yy=np.concatenate((y_test0, y_test1,y_test2), axis=0)
pp=np.concatenate((pred0, pred1,pred2), axis=0)

In [137]:
print(classification_report(yy,pp))
print(confusion_matrix(yy,pp))

             precision    recall  f1-score   support

          F       0.46      0.24      0.32       269
          I       0.63      0.77      0.69       254
          M       0.45      0.55      0.49       313

avg / total       0.51      0.52      0.50       836

[[ 65  41 163]
 [ 10 196  48]
 [ 67  74 172]]


Mejora la precision de I y el recall de M